apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-auth-api.fullname" . }}
  labels:
    {{- include "simple-auth-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "simple-auth-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simple-auth-api.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "simple-auth-api:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: DATABASE_HOST
              value: "{{ .Values.database.host }}"
            - name: DATABASE_PORT
              value: "{{ .Values.database.port }}"
            - name: DATABASE_USERNAME
              value: "{{ .Values.database.username }}"
            - name: DATABASE_PASSWORD
              value: "{{ .Values.database.password }}"
            - name: DATABASE_NAME
              value: "{{ .Values.database.name }}"
