apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-auth-api.fullname" . }}
  labels:
    {{- include "simple-auth-api.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "simple-auth-api.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
